language: ruby
rvm:
  - 2.3.1
cache: bundler
bundler_args: --jobs=2
script:
  - psql -c 'create database squashapp_test;' -U postgres
  - bundle exec rake spec
services:
  - postgresql
addons:
  postgresql: "9.6"
group: stable
dist: trusty
os: linux
